### ISSUE TITLE
Depths of Despair quest start overlay has bugged requirements list in overlay

### ISSUE THREAD

**Issue by Nightfirecat** [Zoinkwiz/quest-helper#496]
![depths-of-despair-overlay-bug](https://user-images.githubusercontent.com/2199511/137398468-2b28db88-6d94-4110-a4a7-e0435e81563a.png)

**Comment by Zoinkwiz** [comment]
Hopefully this is fixed with https://github.com/Zoinkwiz/quest-helper/commit/363a9f17c4fb190aa80579b54388ec24e39cc079#diff-69c4272badb301a12cba72b9729c783eaddf47dade1cc95861de8d78bf83fca6, if anyone else encounters this please do report it.

**Comment by Nightfirecat** [comment]
This is sadly not fixed. I can confirm in shattered relic leagues that having all requirements besides favour leads to the same overlay bug mentioned in the original post here.

**Comment by Nightfirecat** [comment]
That is, I have Client of Kourend, X Marks the Spot, above 18 Agility, and 0% favour.
